steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sicuro_ruby:0.1', '.']
    dir: 'ruby'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sicuro_javascript:0.1', '.']
    dir: 'javascript'
images: ['gcr.io/$PROJECT_ID/sicuro_ruby:0.1', 'gcr.io/$PROJECT_ID/sicuro_javascript:0.1']  