version: '2'
services:
  redis:
    image: redis:alpine
    ports: 
      - "6378:6379"
  postgres:
    image: postgres:alpine
    ports: 
      - "5431:5432"
  mongodb:
    image: mongo:3.4.3
    ports:
      - "27017:27017"