version: '2'
services:
  app:
    image: ubuntu:latest
    command: bash
    links:
     - redis
     - postgres
    env:
      - DATABASE_URL=postgres://postgres@postgres:5432
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:alpine
    ports: 
      - "6378:6379"
  postgres:
    image: postgres:alpine
    ports: 
      - "5431:5432"
  mongodb:
    image: mongo:3.4.3
    ports:
      - "27017:27017"